on:
  push:
    tags:
    - '*'

jobs:
  release_policy:
    runs-on: ubuntu-latest
    name: build
    steps:
    
    - uses: actions/checkout@v2

    - name: Build Policy 
      id: aserto-build
      uses: aserto-dev/aserto-build-action@v1
      with:
        source_path: "src"
        target_path: "build"
        target_file: "bundle.tar.gz"
        build_options: "--revision $GITHUB_SHA"
        verbose: true

    - name: Release Policy
      id: release
      uses: xresloader/upload-to-github-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "build/bundle.tar.gz"
        tags: true
        draft: false
        verbose: true

    - name: Push Policy 
      id: aserto-push
      uses: aserto-dev/aserto-push-action@v2
      env:
        ASERTO_PUSH_KEY: ${{ secrets.ASERTO_ENG_PUSH_KEY }}
      with:
        policy_registry: ${{ secrets.ASERTO_POLICY_REGISTRY }}
        bundle: build/bundle.tar.gz
        release_id: ${{ steps.release.outputs.release_id }}
        verbose: true
